[langserver]
dreamchecker = true

[debugger]
engine = "auxtools"
<<<<<<< HEAD
=======

#[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true
>>>>>>> 5204f5a6d9 (Merge pull request #13991 from Putnam3145/auxtools-atmos)

[dmdoc]
use_typepath_names = true
